# Generated by Django 3.2.10 on 2022-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='aaa', max_length=3000, verbose_name='商品説明'),
            preserve_default=False,
        ),
    ]
